### ISSUE TITLE
Potential problem with client actions resolving on server

### ISSUE THREAD

**Issue by lostpebble** [brillout/wildcard-api#5]
Hi @brillout 

Today I noticed something strange, and I thought I'd notify you now - I might run some more tests to see if its really an issue on my side or with `wildcard-api` - but the behaviour is new and I'm pretty sure I haven't changed anything with my code and `wildcard-api`.

I'm getting these errors now when my server is running "client" endpoints:

```
****************************************
************* Stack Trace **************
****************************************
    at getCallStack (C:\dev\_projects\vibescout-web-workspace\node_modules\reassert\assert.js:170:27)
    at Function.reassert (C:\dev\_projects\vibescout-web-workspace\node_modules\reassert\assert.js:25:21)
    at Function.module.exports [as usage] (C:\dev\_projects\vibescout-web-workspace\node_modules\reassert\usage.js:9:19)
    at assert_context (C:\dev\_projects\vibescout-web-workspace\node_modules\wildcard-api\server\WildcardApi.js:541:14)
    at Object.set (C:\dev\_projects\vibescout-web-workspace\node_modules\wildcard-api\server\WildcardApi.js:527:5)
    at Function.assign (<anonymous>)
    at runEndpoint (C:\dev\_projects\vibescout-web-workspace\node_modules\wildcard-api\server\WildcardApi.js:273:12)
    at Object.__directCall (C:\dev\_projects\vibescout-web-workspace\node_modules\wildcard-api\server\WildcardApi.js:99:45)


****************************************
************* Wrong Usage **************
****************************************
Cannot get context `this.endpointName`.
Context is missing while running the Wildcard client on Node.js.
Make sure to add the request context with `bind`: `endpoints.postSearchQuery.bind(requestContext)`.
```

The only difference between now and a couple days ago is that I updated my Node.js installation to version 12.1.0 - so I think that there may be an issue with that version.

I'm going to try and downgrade and see.

**Comment by lostpebble** [comment]
These endpoints function perfectly fine when run on the browser btw - its only when I try and run my client endpoints on the server that this happens (I use server-rendering for my React apps and my React app needs to run client endpoints while rendering).

**Comment by lostpebble** [comment]
Okay, its not a problem with Node.js 12 as I tried changing and got the same errors.

It seems to be a problem with setting the `requestContext` on my endpoints on the client... But I never did that before and it worked fine. I see things changed somehow after version `0.1.2` which broke my SSR.

My endpoints do not really make use of context (headers etc.) as I pass everything needed to them in my arguments.

Having to do something like this every time I want to call a simple endpoint seems very verbose when I don't require any of that context in my app:

```js
const {endpoints} = require('wildcard-api/client');

async function getInitialProps({isNodejs, request: {headers}={}}) {
  let {getLandingPageData} = endpoints;

  // When calling `getLandingPageData` on the server, we have to
  // preserve the request context.
  if( isNodejs ) {
    // E.g. we pass on the HTTP headers of the original HTTP request:
    const context = {headers};
    getLandingPageData = getLandingPageData.bind(context);
  }

  const landingPageData = await getLandingPageData();
  return landingPageData;
}
```

Is there a way that you can revert to the previous behaviour for times when context is not required?

**Comment by brillout** [comment]
I will have a look now

**Comment by lostpebble** [comment]
Cool, thanks - I updated my last post too with extra details of my use case.

**Comment by brillout** [comment]
I know what's going on but I have to run some errands. I'll fix this later today.

**Comment by brillout** [comment]
Fixed & new version published as `wildcard-api@0.1.4`. You may now omit bind entirely, e.g.: https://github.com/brillout/wildcard-api/blob/master/test/tests/ssr.js

**Comment by brillout** [comment]
As for your questions I will reply tomorrow. I've simplified how Wildcard works, it should be easier to grasp now. (I removed the notion of context, more tmrw.)

**Comment by brillout** [comment]
I improved the FAQ entry "Does it work with SSR?": https://github.com/brillout/wildcard-api#does-it-work-with-ssr

The bottom line is: 

> When used in the browser, the Wildcard client makes an HTTP request to your server which calls getApiResponse. But when used in Node.js, the Wildcard client directly calls your endpoint function, without doing any HTTP request. That's why you need to bind() the request object.

Check the FAQ entry for more explanation.

I hope this clarifies things. Let me know if not and I'll improve the explanation.

Btw. I want to make Wildcard more popular. Any idea how I can do so?

**Comment by lostpebble** [comment]
Thanks for the quick fix! It's working fine for me now, just tested out `0.1.5`.

I see, it all makes sense... if only there was another way to get the context in when calling on Node.js directly - but yea, I do understand the problem here. It seems pretty much impossible to do in any other way.

> Btw. I want to make Wildcard more popular. Any idea how I can do so?

Yea I know that part is always hard. Maybe you could make a video like "Wildcard API in 2 minutes" where you quickly show the features of the project with code and working examples - to show people how truly easy it is. Then you could post that video on Reddit (r/javascript, r/webdev etc.), Twitter and other places.

This is how I plan to advertise one of my projects soon (https://github.com/lostpebble/pullstate). I think people just have short attention spans, and are already using different technology - but if you can show them very quickly (2 minutes maximum) how awesome and easy to use your project is, I think you could get new users.

**Comment by brillout** [comment]
> Thanks for the quick fix

Thanks for believing in Wildcard.

>  It seems pretty much impossible to do in any other way.

Yes I'm afraid so. I wished there would be an easier way.

> to show people how truly easy it is

Hm.. yea.. true. That's probably where I could improve: improve the Readme so that understanding Wildcard feels easy and natural. Some parts of the Readme are clunky right now.

I'll be working on it, thanks.

As for videos I'm quite opinionated on this and I believe that text is a vastly superior way to consume information. But yea video is easier to consume. For now I'd rather convince on the merits of Wildcard being and easy and efficient tool.

**Comment by lostpebble** [comment]
> As for videos I'm quite opinionated on this and I believe that text is a vastly superior way to consume information. But yea video is easier to consume. For now I'd rather convince on the merits of Wildcard being and easy and efficient tool.

Yea for sure. For documentation and wanting to know more about a project, text is by far superiour - but for promotional purposes, a quick video could be a good catalyst to give people who would never even land on your github page a way to see what they're missing out on in a very easily consumable way (and fun way, if you can make the video slightly interersting).

Its purely an additional opportunity to get exposure, and not gaurenteed to work of course. I'm gonna give it a go on my little project and I'll let you know how it goes :)

**Comment by brillout** [comment]
> Yea for sure. For documentation and wanting to know more about a project, text is by far superiour - but for promotional purposes, a quick video could be a good catalyst to give people who would never even land on your github page a way to see what they're missing out on in a very easily consumable way (and fun way, if you can make the video slightly interersting).

Ok yes makes sense.

> I'm gonna give it a go on my little project and I'll let you know how it goes :)

Yea! And would be funny to see your face ;-).

**Comment by brillout** [comment]
Ah and I've made couple of changes to the readme. I believe it's a bit better now.
